Models/Views/FormViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreMvcHelpers.Models.Views
{
    public class FormViewModel
    {
        [Display(Name = "Имя")]
        [Required(ErrorMessage = "Укажите имя")]
        [MinLength(2, ErrorMessage = "Минимальная длина имени - 2 символа")]
        [MaxLength(64, ErrorMessage = "Максимальная длина имени - 64 символа")]
        public string? FirstName { get; set; }

        [Display(Name = "Фамилия")]
        [Required(ErrorMessage = "Укажите фамилию")]
        [MinLength(2, ErrorMessage = "Минимальная длина фамилии - 2 символа")]
        [MaxLength(64, ErrorMessage = "Максимальная длина фамилии - 64 символа")]
        public string? LastName { get; set; }
    }
}

Controllers/FormController.cs
using AspNetCoreMvcHelpers.Filters;
using AspNetCoreMvcHelpers.Models.Views;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreMvcHelpers.Controllers
{
    public class FormController : Controller
    {
        [HttpGet]
        [ServiceFilter(typeof(LogActionFilter))]
        public IActionResult Index()
        {
            return View(new FormViewModel());
        }

        [HttpPost]
        public IActionResult Process([FromForm] FormViewModel model)
        {
            if (!ModelState.IsValid)
                return View("Index");

            return View("Result", model);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreMvcHelpers.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Form/Index.cshtml
@model FormViewModel

<h1>Анкета</h1>
<hr />

@Html.ActionLink("Вернуться на главную страницу", "Index", "Home")
<hr />

@using (Html.BeginForm("Process", "Form", FormMethod.Post))
{
    <div class="mb-3">
        @Html.BootstrapLabelFor(m => m.FirstName)
        @Html.EditorFor(m => m.FirstName)
        @Html.BootstrapValidationMessageFor(m => m.FirstName)
    </div>

    <div class="mb-3">
        @Html.BootstrapLabelFor(m => m.LastName)
        @Html.EditorFor(m => m.LastName)
        @Html.BootstrapValidationMessageFor(m => m.LastName)
    </div>

    <div class="mb-3">
        @Html.BootstrapSubmit("Сохранить анкету", "bi-floppy")
    </div>
}

Views/Form/Result.cshtml
@model FormViewModel

<h1>Данные из анкеты</h1>
<hr />

@Html.ActionLink("Вернуться на главную страницу", "Index", "Home")
<hr />

<p>
    <b>Имя</b>: @Model.FirstName
</p>

<p>
    <b>Фамилия</b>: @Model.LastName
</p>

Views/Home/Index.cshtml
@using System.Drawing
<h1>Главная страница</h1>
<hr />

@Html.ActionLink("Перейти к анкете", "Index", "Form")
<hr />

@Html.ColoredText("Hello, world!", AspNetCoreMvcHelpers.Helpers.Html.Color.Red)
@Html.ColoredText("Hello, world!", AspNetCoreMvcHelpers.Helpers.Html.Color.Green)
@Html.ColoredText("Hello, world!", AspNetCoreMvcHelpers.Helpers.Html.Color.Blue)

<hr />

<bootstrap-button>Привет, мир!</bootstrap-button>

Views/Shared/EditorTemplates/String.cshtml
@model string

@Html.TextBox("", ViewData.TemplateInfo.FormattedModelValue, new {
    @class = "form-control"
})

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
        <title>Веб-приложение</title>
    </head>
    <body>
        <div class="container-md mt-3">
            @RenderBody()
        </div>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>